- name: Run using a project directory
  hosts: [pihole]
  gather_facts: yes
  become: true
  tasks:
    - name: Baseline
      ansible.builtin.include_tasks: tasks/baseline.yml

    - name: Docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: ensure data directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0774'
        owner: 1000
        group: 1000
      loop:
        - /opt/pihole
        - /opt/pihole/etc-pihole
        - /opt/pihole/etc-dnsmasq.d
    - name: add internal host names
      ansible.builtin.copy:
        dest: /opt/pihole/etc-pihole/custom.list
        src: ./compose/pihole/custom.list
        owner: root
        group: root
        mode: '0644'
      register: custom_host_changed
    - name: install python docker
      ansible.builtin.apt:
        name:
          - python3-docker
          - docker-compose
        state: present
    - name: deploy compose file
      ansible.builtin.copy:
        src: ./compose/pihole/compose.yml
        dest: /opt/pihole/compose.yml
        mode: '0644'
    - name: mask systemd-resolv #this is needed because pihole listens to port 53
      ansible.builtin.systemd_service:
        name: systemd-resolved
        state: stopped
        masked: true
    - debug:
        var: custom_host_changed
    - name: Tear down existing services
      docker_compose:
        project_src: /opt/pihole/
        state: absent
        files: compose.yml
      when: custom_host_changed is changed
    - name: Create and start services
      docker_compose:
        project_src: /opt/pihole/
        files: compose.yml
      register: output
      when: custom_host_changed is changed
    - debug:
        var: output
      when: custom_host_changed is changed
    - name: Run `docker-compose up` again
      docker_compose:
        project_src: /opt/pihole/
        build: no
        files: compose.yml
      when: custom_host_changed is changed
      register: output
    - debug:
        var: output
      when: custom_host_changed is changed
    - assert:
        that: "not output.changed "
      when: custom_host_changed is changed