- name: Run using a project directory
  hosts: [semaphore]
  gather_facts: yes
  become: true
  tasks:
    - name: Tear down existing services
      docker_compose:
        project_src: /opt/semaphore
        state: absent
        files: compose.yml
    - name: Create and start services
      docker_compose:
        project_src: /opt/semaphore
        files: compose.yml
      register: output
    - debug:
        var: output
    - name: Run `docker-compose up` again
      docker_compose:
        project_src: /opt/semaphore
        build: no
        files: compose.yml
      register: output
    - debug:
        var: output
    - assert:
        that: "not output.changed "