---
- name: Debian Config - Debian Baseline & Docker Install
  hosts: docker_hosts
  gather_facts: true
  become: true
  tasks:
    - name: Baseline
      ansible.builtin.include_tasks: tasks/baseline.yml
    
    - name: Docker
      ansible.builtin.include_tasks: tasks/docker.yml
