---
- name: setup qemu agent
  ansible.builtin.include_tasks: tasks/proxmox_guest.yml
- name: Upgrade All Packages To The Latest Version
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
- name: Install Core Dependencies, Clean APT, & Remove Old Programs
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - htop
      - ncdu
      - sudo
      - unattended-upgrades
      - vim
      - git
      - zsh
    state: present
    install_recommends: true
    autoremove: true
    autoclean: true
- name: Add ansible user
  ansible.builtin.user:
    name: ansible_u
    comment: John Doe Ansible
    uid: 1040
    groups: sudo,adm
- name: "Add authorized keys"
  authorized_key:
    user: "ansible_u"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFDv1NKKDovf43f6128KUGZvDHdm824wR/+gxfcfQrlM"
