---
- name: Add Docker Module Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: yes
- name: install python docker
  ansible.builtin.apt:
    name:
      - python3-docker
      - docker-compose
    state: present

- name: Install Docker Engine, Docker CLI, Containerd, & Docker Compose
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-buildx-plugin
    state: present
    install_recommends: true

- name: Set Docker Registry Proxy Configuration
  ansible.builtin.copy:
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: '0644'
    content: |
      {
              "metrics-addr": "127.0.0.1:9323",
              "experimental": true
      }
